version: '3'
services:
 mysql:           # 服务的名称    
  restart: always   # 代表只要docker启动，那么这个容器就跟着一起启动    
  image: daocloud.io/library/mysql:5.6.24  # 指定镜像路径    
  container_name: mysql  # 指定容器名称    
  ports: 
   - 3306:3306   #  指定端口号的映射  
  command:
   --character-set-server=utf8mb4
   --collation-server=utf8mb4_general_ci 
  environment: 
   MYSQL_ROOT_PASSWORD: 'root'   # 指定MySQL的ROOT用户登录密码      
   TZ: Asia/Shanghai        # 指定时区    
  volumes: 
   - ./mysql:/var/lib/mysql:z   # 映射数据卷  
 tomcat:    
  restart: always    
  image: daocloud.io/library/tomcat:8.5.15-jre8
  container_name: tomcat    
  ports: 
   - 8080:8080 
  environment:
   TZ: Asia/Shanghai    
  volumes:  
   - ./tomcat/webapps:/usr/local/tomcat/webapps:z    
   - ./tomcat/logs:/usr/local/tomcat/logs:z
 nginx:
  restart: always
  image: daocloud.io/library/nginx:1.13.2
  container_name: nginx
  command: [nginx-debug, '-g', 'daemon off;']
  ports:
   - 80:80
  volumes:
   - ./tomcat/webapps:/usr/share/nginx/html:z
   - ./nginx/nginx.conf:/etc/nginx/nginx.conf:z
   - ./nginx/logs:/var/log/nginx:z
  # - ./nginx/conf.d:/etc/nginx/conf.d:z
  environment:
   TZ: Asia/Shanghai



